### PR TITLE
cleaned up list in gen.py

### PR DESCRIPTION
**Pull request by jojokarlin**
Seems without permissions, forking is necessary.

### CODE REVIEW

**Comment by jojokarlin** [comment]
Sara! The bot is up and running on my computer. I am still working on getting it to retweet particular people/hashtags.

**Comment by tmober** [comment]
Cool! Somehow I seem to be on this thread as well! Still figuring out the ins-and-outs of GitHub. Can’t wait to see what the Tweets look like!

Sincerely,

Teresa

**Comment by jojokarlin** [comment]
I think because you are a contributor you are automatically signed up to
receive comments.
The tweets are live online, so you can just pop on twitter and follow our
bot to see.
-Jojo

On Tue, Mar 29, 2016 at 11:47 AM, trezzao notifications@github.com wrote:

> Cool! Somehow I seem to be on this thread as well! Still figuring out the
> ins-and-outs of GitHub. Can’t wait to see what the Tweets look like!
> 
> Sincerely,
> 
> Teresa
> 
> > On Mar 29, 2016, at 11:45 AM, Jojo notifications@github.com wrote:
> > 
> > Sara! The bot is up and running on my computer. I am still working on
> > getting it to retweet particular people/hashtags.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub <
> > https://github.com/sev2109/itpbot/pull/2#issuecomment-202967822>
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/sev2109/itpbot/pull/2#issuecomment-202968720

## 

Jojo Karlin
508.725.5450
jojokarlin.com

**Comment by tmober** [comment]
Looking good! We may want to tweak some of the parameters so that the sequence of words is a little more coherent. Liking it so far, though!

Sincerely,

Teresa

**Comment by sev2109** [comment]
Sorry ladies I was at meetings all day! Just merged changes

**Pull request merged**
